### ISSUE TITLE
Remove Reload confirmation

### ISSUE THREAD

**Issue by hkedia321** [hkedia321/scrum_helper_extension#16]
**Actual Behaviour**

On pressing the `Refresh this page to apply` button, the page confirms from the user before refreshing.

**Expected Behaviour**

When the user presses the refresh button, the page should refresh without asking for confirmation

**Screenshots of the issue**
On pressing this button:
![image](https://user-images.githubusercontent.com/17807257/32139120-872ae5f0-bc5e-11e7-87de-0b9ecd2936cc.png)
This alert is shown:
![image](https://user-images.githubusercontent.com/17807257/32139124-9f895848-bc5e-11e7-8bf2-424e5fcca93d.png)

This alert should not be shown, and the page should refresh.

If you are interested to work on this, please leave a comment below and send a PR.

**Comment by NamanArora** [comment]
Hi I would like to try and fix this..
